Clang format
altlinux/admc pull request #399
Opened 2023-02-14 13:31 UTC by iv-m

2023-02-14 13:32 UTC, iv-m commented
@august-alt  plz take a look.

2023-02-14 16:44 UTC, august-alt commented on src/admc/tabs/attributes_tab.cpp
> +            {AttributesColumn_Type, tr("Type")}});
Maybe we should disable clang-format here it would definitely improve readability.

2023-02-14 17:00 UTC, august-alt commented
@iv-m If we now try to build admc on machine that has no clang-format cmake will not allow us to do so. 
```
cmake ..
-- Project version is: 0.11.2
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project version is: 
CMake Error at cmake/ClangFormat.cmake:17 (message):
  ClangFormat: clang-format not found! Aborting
Call Stack (most recent call first):
  cmake/ClangFormat.cmake:51 (prefix_clangformat_setup)
  src/admc/CMakeLists.txt:195 (target_clangformat_setup)


-- Configuring incomplete, errors occurred!
See also "admc/build/CMakeFiles/CMakeOutput.log".
```
Probably if we add an option to skip clang-format and set this option to be on by default it will help us to mitigate this issue. Another issue is that this PR does not provide changes to .gear/admc.spec file to ensure that build system has clang-fromat installed.

2023-02-14 17:05 UTC, august-alt requested changes
We should either provide changes to spec file and update documentation stating that clang-format is now required to do the build or provide option to skip it. This will also be helpful when we start implementing CI in near future. To additional information on the issue please refer to my comments on this PR.

2023-02-14 21:08 UTC, iv-m commented
> @iv-m If we now try to build admc on machine that has no clang-format cmake will not allow us to do so.

Like it's something bad =D

Jokes aside, I've updated ClangFormat.cmake to generate a warning instead of `FATAL_ERROR` when the `clang-format` executable is not found:

```
CMake Warning at cmake/ClangFormat.cmake:17 (message):
  clang-format executable not found! ClangFormat targets will not be
  generated.
Call Stack (most recent call first):
  cmake/ClangFormat.cmake:53 (prefix_clangformat_setup)
  src/admc/CMakeLists.txt:195 (target_clangformat_setup)
```

This warning is generated twice (once for `adldap` and once for `admc`), which is not perfect but  I find it acceptable. Of course, when  `clang-format` is not found, `clangformat` target is not generated:

```
$ make clangformat
make: *** No rule to make target 'clangformat'.  Stop.
```

2023-02-14 21:15 UTC, iv-m commented on src/admc/tabs/attributes_tab.cpp
> +            {AttributesColumn_Type, tr("Type")}});
I missed this in my `Initializer list formatting` commit. When the last item of an initializer list does not have a trailing comma, `clang-format` does something weird and I'm yet to figure out how to avoid that without disabling autoformatting.

I've amended that commit, and now, with and addition of a comma, the formatting of this particular piece of code looks ok.

2023-02-15 03:51 UTC, august-alt approved these changes
Build successful, all tests have passed. Approved.

2023-02-15 03:54 UTC, merged