Icon themes: Active-Directory (line, duotone, color)
altlinux/admc pull request #425
Opened 2023-11-15 14:39 UTC by LenkaDEA

Added icon themes: Active-Directory-line, Active-Directory-duotone, Active-Directory-color
Icon themes are set separately: https://github.com/LenkaDEA/admc_icons/tree/themes

2023-11-22 12:47 UTC, Samael340 requested changes

2023-11-23 06:44 UTC, mastersin commented on src/admc/settings.cpp
> +    QSettings::setPath(QSettings::NativeFormat, QSettings::SystemScope, "/etc/icon-theme-ActiveDirectory");
А что такое /etc/icon-theme-ActiveDirectory ?
Это файл настройки или каталог? Если каталог, то для чего?

2023-11-23 10:02 UTC, LenkaDEA commented on src/admc/settings.cpp
> +    QSettings::setPath(QSettings::NativeFormat, QSettings::SystemScope, "/etc/icon-theme-ActiveDirectory");
Это каталог в котором лежит файл конфигураций с темами иконок. 
Этот каталог и файл конфигураций в нем создаются при установке пакета с темами значков:
https://github.com/LenkaDEA/admc_icons/tree/themes

2023-11-23 12:09 UTC, LenkaDEA commented on src/admc/settings.cpp
> +        name_theme_list.push_back(set.value(name_theme).toString());
Здесь я читаю все темы из конфига. Если темы не установлены, то они и не будут доступны для выбора пользователя.
Что именно сделать как там?

2023-11-23 13:52 UTC, Samael340 commented on src/admc/settings.cpp
> +        name_theme_list.push_back(set.value(name_theme).toString());
https://github.com/altlinux/admc/pull/369/commits/7352f78d59d1643b720cdb134f780147735f1a15#diff-97bc1ba0dc658854c9255d6c6a716e0f785f15abb59e7af85b2278a6038ade86R116

2023-11-26 12:57 UTC, LenkaDEA commented on src/admc/settings.cpp
> +        name_theme_list.push_back(set.value(name_theme).toString());
Если я верно поняла твою мысль, то ты хочешь, чтоб просматривался весь каталог с темами, тем самым в списке выбора тем появились доп темы, что есть у пользователя. Верно я тебя поняла? 
Если да, то считаю, что это лишний функционал. 
1. Нам не известно, как доп темы (которые установлены у пользователя на системе) будут дружить с нашим приложением.
2. Если пользователь захочет поменять тему, то он поменяет ее скорее на всей системе. 
3. Наши темы более полные для нашего приложения, так что использовать, с большей вероятность, будут их, потому что это удобнее. 

Если я не права, то поясните, потому это будет не лишним, пожалуйста.

2024-12-02 14:54 UTC, closed without merging